name: 'Run DeepCode'
description: 'Execute DeepCode CLI for code generation'

inputs:
  model_name:
    description: 'Model to use'
    required: false
    default: 'claude-sonnet-4-5'
  prompt_file:
    description: 'Path to prompt file'
    required: true
  output_dir:
    description: 'Output directory for generated code'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install deepcode-hku
      shell: bash
      run: |
        pip install --upgrade pip
        pip install deepcode-hku

    - name: Verify deepcode installation
      shell: bash
      run: |
        deepcode --version
        which deepcode

    - name: Create output directory
      shell: bash
      run: mkdir -p "${{ inputs.output_dir }}"

    - name: Run DeepCode
      shell: bash
      run: |
        deepcode \
          --model "${{ inputs.model_name }}" \
          --prompt-file "${{ inputs.prompt_file }}" \
          --output-dir "${{ inputs.output_dir }}"

    - name: List generated files
      shell: bash
      if: always()
      run: |
        echo "=== Generated Files ==="
        if [ -d "${{ inputs.output_dir }}" ]; then
          find "${{ inputs.output_dir }}" -type f | head -20
        else
          echo "Output directory not found"
        fi
